
Vagrant.configure("2") do |config|

    config.vm.define "cryptotux-bitcoin-server" do |machine|
        machine.vm.network "private_network", ip: "172.17.177.22"
        machine.vm.box = "ubuntu/bionic64"
        machine.vm.provider "virtualbox" do |vb|
            vb.name = "cryptotux-bitcoin-server"
        end 
        machine.vm.hostname = "cryptotux-bitcoin-server"
        machine.vm.synced_folder "..", "/vagrant", owner: "vagrant",
  group: "vagrant", mount_options: ["uid=1234", "gid=1234"]
        machine.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.verbose = "vvv"
            ansible.playbook = "/vagrant/provisioning/playbook-bitcoin-server.yml"
        end
    end

    
end