
Vagrant.configure("2") do |config|

    config.vm.define "cryptotux-eth-server" do |machine|
        machine.vm.network "private_network", ip: "172.17.177.21"
        machine.vm.network "forwarded_port", guest: 3000, host: 3000
        machine.vm.box = "ubuntu/bionic64"
        machine.vm.provider "virtualbox" do |vb|
            vb.name = "cryptotux-eth-server"
        end 
        machine.vm.synced_folder "..", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["uid=1234", "gid=1234"]
        machine.vm.hostname = "cryptotux-eth-server"
        machine.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.verbose = "vvv"
            ansible.galaxy_role_file = "requirements.yml"
            ansible.playbook = "/vagrant/provisioning/playbook-eth-server.yml"
        end
    end
end